[package]
name = "perfect-form"
version = "0.1.0"
edition = "2024"
default-run = "perfect-form"

[workspace]
members = [".", "macros", "migration"]

[dependencies]
argon2 = "0.5"
clap = { version = "4.6", features = ["derive"] }
jsonwebtoken = "9"
migration = { path = "migration" }
rpassword = "7"
sea-orm = { version = "2.0", features = ["runtime-tokio-rustls", "sqlx-sqlite"] }
sea-orm-cli = { version = "2.0", default-features = false, features = ["cli"] }
sea-orm-migration = { version = "2.0", features = ["runtime-tokio-rustls", "sqlx-sqlite"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
toml = "0.8"
perfect-form-macros = { path = "macros" }
topcoat = { version = "0.6.2", features = ["htmx"] }
