version = 1

[schema]

[[schema.tables]]
id = 0
name = "users"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "I32"
storage_ty = { Integer = 4 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "email"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "password_hash"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "admin"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_users_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_users_by_email"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "users_roles"
primary_key = { columns = [{ table = 1, index = 0 }, { table = 1, index = 1 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "user_id"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "role_id"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_users_roles_by_user_id_and_role_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }, { column = { table = 1, index = 1 }, op = "Eq", scope = "Local" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_users_roles_by_user_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 1, index = 2 }
name = "index_users_roles_by_role_id"
on = 1
columns = [{ column = { table = 1, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 2
name = "roles"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "I32"
storage_ty = { Integer = 4 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_roles_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_roles_by_name"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true
